/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type ProjectoverviewOverridesProps = {
    Projectoverview?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 16"?: PrimitiveOverrideProps<ViewProps>;
    Describtion?: PrimitiveOverrideProps<TextProps>;
    "TaskFlow is an intuitive task management system designed to help teams collaborate and manage their projects with ease. It offers powerful features such as task tracking, project organization, scheduling, and communication tools to keep teams organized and on top of their projects."?: PrimitiveOverrideProps<TextProps>;
    "Vector 2"?: PrimitiveOverrideProps<IconProps>;
    "Frame 292371526"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 27"?: PrimitiveOverrideProps<FlexProps>;
    Folder2371528?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Folder"?: PrimitiveOverrideProps<ViewProps>;
    Folder2371530?: PrimitiveOverrideProps<ViewProps>;
    "Folder-2"?: PrimitiveOverrideProps<IconProps>;
    Vector2371532?: PrimitiveOverrideProps<IconProps>;
    Projects?: PrimitiveOverrideProps<TextProps>;
    "Vector 3"?: PrimitiveOverrideProps<IconProps>;
    "Frame 28"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 82371536"?: PrimitiveOverrideProps<ViewProps>;
    "Team projects2371537"?: PrimitiveOverrideProps<TextProps>;
    "Vector 42371538"?: PrimitiveOverrideProps<IconProps>;
    "Frame 292371539"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 82371540"?: PrimitiveOverrideProps<ViewProps>;
    Fashion2371541?: PrimitiveOverrideProps<TextProps>;
    "Frame 90"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 82371543"?: PrimitiveOverrideProps<ViewProps>;
    Cloth2371544?: PrimitiveOverrideProps<TextProps>;
    "Frame 34"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42371546"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 12371547"?: PrimitiveOverrideProps<IconProps>;
    "Group 82371548"?: PrimitiveOverrideProps<ViewProps>;
    "Project 1"?: PrimitiveOverrideProps<TextProps>;
    "Small and Consices headline2371550"?: PrimitiveOverrideProps<TextProps>;
    "Frame 332371551"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 322371552"?: PrimitiveOverrideProps<FlexProps>;
    CREATED2371553?: PrimitiveOverrideProps<TextProps>;
    "Mar 23, 10:34 PM2371554"?: PrimitiveOverrideProps<TextProps>;
    "Frame 312371555"?: PrimitiveOverrideProps<FlexProps>;
    DEADLINE2371556?: PrimitiveOverrideProps<TextProps>;
    "Jun 02, 04:01 PM2371557"?: PrimitiveOverrideProps<TextProps>;
    "Frame 332371558"?: PrimitiveOverrideProps<FlexProps>;
    "TRACKED TIME2371559"?: PrimitiveOverrideProps<TextProps>;
    "10H 32M2371560"?: PrimitiveOverrideProps<TextProps>;
    "Group 6"?: PrimitiveOverrideProps<ViewProps>;
    Vector2371562?: PrimitiveOverrideProps<IconProps>;
    Edit2371563?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bold/Edit2371564"?: PrimitiveOverrideProps<ViewProps>;
    Edit2371565?: PrimitiveOverrideProps<ViewProps>;
    Vector2371566?: PrimitiveOverrideProps<IconProps>;
    Edit2371567?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bold/Edit2371568"?: PrimitiveOverrideProps<ViewProps>;
    Edit2371569?: PrimitiveOverrideProps<ViewProps>;
    Vector2371570?: PrimitiveOverrideProps<IconProps>;
    "Frame 91"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42371572"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 12371573"?: PrimitiveOverrideProps<IconProps>;
    "Group 82371574"?: PrimitiveOverrideProps<ViewProps>;
    Cloth2371575?: PrimitiveOverrideProps<TextProps>;
    "Small and Consices headline2371576"?: PrimitiveOverrideProps<TextProps>;
    "Frame 332371577"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 322371578"?: PrimitiveOverrideProps<FlexProps>;
    CREATED2371579?: PrimitiveOverrideProps<TextProps>;
    "Mar 23, 10:34 PM2371580"?: PrimitiveOverrideProps<TextProps>;
    "Frame 312371581"?: PrimitiveOverrideProps<FlexProps>;
    DEADLINE2371582?: PrimitiveOverrideProps<TextProps>;
    "Jun 02, 04:01 PM2371583"?: PrimitiveOverrideProps<TextProps>;
    "Frame 332371584"?: PrimitiveOverrideProps<FlexProps>;
    "TRACKED TIME2371585"?: PrimitiveOverrideProps<TextProps>;
    "10H 32M2371586"?: PrimitiveOverrideProps<TextProps>;
    "Frame 88"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 83"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 35"?: PrimitiveOverrideProps<FlexProps>;
    "Time Circle"?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Time-Circle"?: PrimitiveOverrideProps<ViewProps>;
    "Time-Circle"?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12371593"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42371594"?: PrimitiveOverrideProps<IconProps>;
    "Created At"?: PrimitiveOverrideProps<TextProps>;
    "May, 15 2022 14:23 PM"?: PrimitiveOverrideProps<TextProps>;
    "Frame 84"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 36"?: PrimitiveOverrideProps<FlexProps>;
    Filter2371599?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Filter"?: PrimitiveOverrideProps<ViewProps>;
    Filter2371601?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12371602"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42371603"?: PrimitiveOverrideProps<IconProps>;
    "Fill-6"?: PrimitiveOverrideProps<IconProps>;
    "Fill-9"?: PrimitiveOverrideProps<IconProps>;
    Tags?: PrimitiveOverrideProps<TextProps>;
    "Frame 43"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 41"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 462371609"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 472371610"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 85"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 37"?: PrimitiveOverrideProps<FlexProps>;
    Profile2371613?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Profile"?: PrimitiveOverrideProps<ViewProps>;
    Profile2371615?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12371616"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42371617"?: PrimitiveOverrideProps<IconProps>;
    Assign?: PrimitiveOverrideProps<TextProps>;
    "Frame 462371619"?: PrimitiveOverrideProps<FlexProps>;
    "@"?: PrimitiveOverrideProps<IconProps>;
    mustafa?: PrimitiveOverrideProps<TextProps>;
    "Frame 86"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 38"?: PrimitiveOverrideProps<FlexProps>;
    "Filter 2"?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Filter-2"?: PrimitiveOverrideProps<ViewProps>;
    "Filter-2"?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12371627"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42371628"?: PrimitiveOverrideProps<IconProps>;
    Group?: PrimitiveOverrideProps<TextProps>;
    "Frame 472371630"?: PrimitiveOverrideProps<FlexProps>;
    "Team projects2371631"?: PrimitiveOverrideProps<TextProps>;
    "Vector 42371632"?: PrimitiveOverrideProps<IconProps>;
    Fashion2371633?: PrimitiveOverrideProps<TextProps>;
    "Frame 87"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 39"?: PrimitiveOverrideProps<FlexProps>;
    Star2371636?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Star"?: PrimitiveOverrideProps<ViewProps>;
    Star2371638?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12371639"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42371640"?: PrimitiveOverrideProps<IconProps>;
    Poriority?: PrimitiveOverrideProps<TextProps>;
    "Frame 48"?: PrimitiveOverrideProps<FlexProps>;
    Small?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type ProjectoverviewProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: ProjectoverviewOverridesProps | undefined | null;
}>;
export default function Projectoverview(props: ProjectoverviewProps): React.ReactElement;
