/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SidebarOverridesProps = {
    Sidebar?: PrimitiveOverrideProps<ViewProps>;
    "Group 4"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1"?: PrimitiveOverrideProps<IconProps>;
    "Star 1"?: PrimitiveOverrideProps<IconProps>;
    TaskFlow?: PrimitiveOverrideProps<TextProps>;
    "Group 13"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 52447"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 3"?: PrimitiveOverrideProps<FlexProps>;
    Category2449?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Category"?: PrimitiveOverrideProps<ViewProps>;
    Category2451?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12452"?: PrimitiveOverrideProps<IconProps>;
    "Combined-Shape"?: PrimitiveOverrideProps<IconProps>;
    Overview?: PrimitiveOverrideProps<TextProps>;
    "Vector 1"?: PrimitiveOverrideProps<IconProps>;
    "Frame 4"?: PrimitiveOverrideProps<FlexProps>;
    Calendar2457?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Calendar"?: PrimitiveOverrideProps<ViewProps>;
    Calendar2459?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12460"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42461"?: PrimitiveOverrideProps<IconProps>;
    "Fill-6"?: PrimitiveOverrideProps<IconProps>;
    "Fill-9"?: PrimitiveOverrideProps<IconProps>;
    Calendar2464?: PrimitiveOverrideProps<TextProps>;
    "Frame 52465"?: PrimitiveOverrideProps<FlexProps>;
    Graph2466?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Graph"?: PrimitiveOverrideProps<ViewProps>;
    Graph2468?: PrimitiveOverrideProps<ViewProps>;
    Path2469?: PrimitiveOverrideProps<IconProps>;
    Path2470?: PrimitiveOverrideProps<IconProps>;
    Analytics?: PrimitiveOverrideProps<TextProps>;
    "Frame 6"?: PrimitiveOverrideProps<FlexProps>;
    Activity2473?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Activity"?: PrimitiveOverrideProps<ViewProps>;
    Activity2475?: PrimitiveOverrideProps<ViewProps>;
    Path_34168?: PrimitiveOverrideProps<IconProps>;
    Ellipse_742?: PrimitiveOverrideProps<IconProps>;
    Activity2478?: PrimitiveOverrideProps<TextProps>;
    "Frame 82479"?: PrimitiveOverrideProps<FlexProps>;
    Folder2480?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Folder"?: PrimitiveOverrideProps<ViewProps>;
    Folder2482?: PrimitiveOverrideProps<ViewProps>;
    "Folder-2"?: PrimitiveOverrideProps<IconProps>;
    Vector?: PrimitiveOverrideProps<IconProps>;
    Projects2485?: PrimitiveOverrideProps<TextProps>;
    "Frame 9"?: PrimitiveOverrideProps<FlexProps>;
    Projects2487?: PrimitiveOverrideProps<TextProps>;
    "Frame 82488"?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Plus2489"?: PrimitiveOverrideProps<ViewProps>;
    Plus2490?: PrimitiveOverrideProps<ViewProps>;
    Path_342002491?: PrimitiveOverrideProps<IconProps>;
    Path_342012492?: PrimitiveOverrideProps<IconProps>;
    "Frame 132493"?: PrimitiveOverrideProps<FlexProps>;
    Tasks?: PrimitiveOverrideProps<TextProps>;
    "Frame 82495"?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Plus2496"?: PrimitiveOverrideProps<ViewProps>;
    Plus2497?: PrimitiveOverrideProps<ViewProps>;
    Path_342002498?: PrimitiveOverrideProps<IconProps>;
    Path_342012499?: PrimitiveOverrideProps<IconProps>;
    "Frame 12"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 132501"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 14"?: PrimitiveOverrideProps<FlexProps>;
    "Group 7"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 15"?: PrimitiveOverrideProps<FlexProps>;
    Wallet2505?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Wallet"?: PrimitiveOverrideProps<ViewProps>;
    Wallet2507?: PrimitiveOverrideProps<ViewProps>;
    "Fill-12508"?: PrimitiveOverrideProps<IconProps>;
    "Fill-42509"?: PrimitiveOverrideProps<IconProps>;
    Oval?: PrimitiveOverrideProps<IconProps>;
    "Frame 18"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 20"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 21"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 22"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 23"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 25"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 26"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 5"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 6"?: PrimitiveOverrideProps<ViewProps>;
    Setting2520?: PrimitiveOverrideProps<ViewProps>;
    "Iconly/Bulk/Setting"?: PrimitiveOverrideProps<ViewProps>;
    Setting2522?: PrimitiveOverrideProps<ViewProps>;
    Path2523?: PrimitiveOverrideProps<IconProps>;
    Path2524?: PrimitiveOverrideProps<IconProps>;
    "Group 5"?: PrimitiveOverrideProps<FlexProps>;
    "Muhammed Ali"?: PrimitiveOverrideProps<TextProps>;
    "Free Account"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type SidebarProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SidebarOverridesProps | undefined | null;
}>;
export default function Sidebar(props: SidebarProps): React.ReactElement;
